ARG dev_cycle=develop
FROM lsstts/develop-env:${dev_cycle}

WORKDIR /usr/src/love/commander
COPY requirements-dev.txt .

# LOVE requirements
RUN source /opt/lsst/software/stack/loadLSST.bash && \
    pip install kafkit[aiohttp] aiokafka lsst_efd_client && \
    pip install -r requirements-dev.txt

# Missing SAL topics
RUN source /opt/lsst/software/stack/loadLSST.bash \
    && source /home/saluser/.setup_salobj.sh \
    && setup ts_sal -t current \
    && /home/saluser/repos/ts_sal/bin/make_idl_files.py Watcher

WORKDIR /home/saluser


CMD ["/usr/src/love/commander/start-daemon-dev.sh"]
