FROM lsstts/develop-env:b41

WORKDIR /usr/src/love/commander
COPY requirements.txt .
RUN source /opt/lsst/software/stack/loadLSST.bash && pip install -r requirements.txt
RUN source /opt/lsst/software/stack/loadLSST.bash \
    && source /home/saluser/repos/ts_sal/setup.env \
    && setup ts_sal -t current \
    && /home/saluser/repos/ts_sal/bin/make_idl_files.py Watcher

WORKDIR /home/saluser

# Flask environment variables
ENV FLASK_APP=/usr/src/love/commander
ENV FLASK_ENV=development
EXPOSE 5000

CMD ["/usr/src/love/commander/start-daemon.sh"]
