# This install file works with `pip install .`
# but not with `python setup.py install`.
import glob
import pathlib
import setuptools
import sys

scm_version_template = """# Generated by setuptools_scm
__all__ = ["__version__"]

__version__ = "{version}"
"""

setuptools.setup(
    name="love-commander",
    description="LSST Operators Visualization Environment (LOVE) service to send SAL commands from http endpoints using salobj.",
    use_scm_version={
        "write_to": "commander/version.py",
        "write_to_template": scm_version_template,
    },
    packages=["commander"],
    license="GPL",
    project_url={
        "Bug Tracker": "https://jira.lsstcorp.org/secure/Dashboard.jspa",
        "Source Code": "https://github.com/lsst-ts/LOVE-commander",
    },
)
