ARG dev_cycle=develop
ARG registry=lsstts
FROM ${registry}/develop-env:${dev_cycle}

WORKDIR /usr/src/love/
COPY requirements-dev.txt .

RUN source /home/saluser/.setup_dev.sh && \
    pip install lsst_efd_client && \
    pip install -r requirements-dev.txt

USER root
CMD ["/usr/src/love/docker/start-daemon-dev.sh"]
