ARG dev_cycle=develop
FROM lsstts/develop-env:${dev_cycle}

WORKDIR /usr/src/love/
COPY . .
COPY docker/run-tests.sh .

RUN source /opt/lsst/software/stack/loadLSST.bash && \
    pip install lsst_efd_client && \
    pip install -r requirements-dev.txt

CMD ["/usr/src/love/run-tests.sh"]
